config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :students, only: [:index, :show]

  get '/students/:id/activate', to: 'students#activate', as: 'activate_student'

end

app/models/concerns/defaults.rb
module Defaults
  # from this blog: http://mrkris.com/2015/02/08/setting-default-values-in-active-record/
  # Added to instance of object
  included do
    after_initialize :apply_default_values
  end

  # Callback for setting default values
  def apply_default_values
    self.class.defaults.each do |attribute, param|
      next unless self.send(attribute).nil?
      value = param.respond_to?(:call) ? param.call(self) : param
      self[attribute] = value
    end
  end

app/models/student.rb
class Student < ActiveRecord::Base
  def to_s
    self.first_name + " " + self.last_name
  end

  def active_status
    self.active == false ? "inactive" : "active"
  end

  def reverse_status
    self.active == false ? self.update(active: true) : self.update(active: false)
  end
end

app/models/turtle.rb
class Turtle < ActiveRecord::Base
  def display
    self.name + " is " + self.age.to_s + " years old"
  end
end

app/controllers/activate_student_controller.rb
class ActivateStudentController < ApplicationController

  def show
    @student = Student.find(params[:id])

    case @student.active
        when false
            @student.active = true
        when true
            @student.active = false
    end   
    @student.save   
    redirect_to "/students/#{@student.id}"
  end 
end

app/controllers/active_student_controller.rb
class ActiveStudentController < ApplicationController
    before_action :set_student, only: :show

  def activate
    set_student
    @student.active =! @student.active 
    @student.save 
    redirect_to student_path
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/static_controller.rb
class StaticController < ApplicationController
  def about
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
before_action :set_student, only: [:show, :activate]
  
def show
end


def activate
    @student.active = !@student.active
    @student.save
    redirect_to student_path(@student)
    
end


private
def set_student
    @student = Student.find(params[:id])
end

end#eoc

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: :show
  
  def index
    @students = Student.all
  end

  def show
    set_student
  end

  def activate
    set_student

    if @student.active == true
      @student.active = false

      @student.save
    else
      @student.active = true 
           
      @student.save
    end

    redirect_to student_path(@student)
  end

  private

    def set_student
      @student = Student.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/activate_student/show.html.erb
<% if @student.active == false %>
  @student.active = true
  @student.save
<% else %>
  @student.active = false
  @student.save
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Arlab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/student/show.html.erb
<h1><%= @student.to_s %></h1>

<p>This student is currently
<%if @student.active%>
<%="active."%>
<%else%>
<%="inactive."%>
</p>
<%end%>

app/views/students/activate.erb
<div>
    <input type="radio" id="active" name="active" checked />
    <label for="active">Huey</label>
</div>

app/views/students/activate.html.erb
<%=@student.active%>

app/views/students/activate_student.html.erb
<div>

</div>

app/views/students/active.html.erb
<% if @student.active %>
  <% @student.active = false %>
  <% @student.save %>
<% else %>
  <% @student.active = true %>
  <% @student.save %>
<% end %>

app/views/students/delete.erb
<div>
  <% @students.each do |student| %>
    <div><%= link_to post.title, post_path(post) %></div>
  <% end %>
</div>

app/views/students/index.html.erb
<div>
  <% @students.each do |student| %>
    <div><%= link_to student.to_s, student_path(student) %></div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>Enter New Student:</h1>
<%= form_tag students_path do %>
    <h3>   <label>Student first name:</label>
    <%= text_field_tag :first_name %><br>  </h3>
      <h3> <label>Student last name:</label>
    <%= text_field_tag :last_name %> <br>  </h3>
    <%= submit_tag "Submit Student" %>
<% end %>

app/views/students/not_used_activate.html.erb
<h1>So The following Student will get activated here:</h1>
<h2><%= "#{@student.first_name} #{@student.last_name}" %></h2>

app/views/students/show.html.erb
<h1><%= @student.to_s %></h1>

<% if @student.active %>
    This student is currently active.
<% else %>
    This student is currently inactive.
<% end %>